name: IRIS ML CI-CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run train.py
      run: python train.py

    - name: Run Tests
      run: pytest

  Push-and-Deploy:
    needs: Build-and-Test
    runs-on: ubuntu-latest

    steps:

    - name: Code Checkout
      uses: actions/checkout@v3

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: True
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/iris-ml-app:latest
          ${{ secrets.DOCKER_USERNAME }}/iris-ml-app:${{ github.run_number }}

  