name: IRIS ML CI-CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Install Dependencies
      uses: pip install -r requirements.txt

    - name: Run Tests
      run: pytest

  Push-and-Deploy:
    needs: Build-and-Test
    runs-on: ubuntu-latest

    steps:

    - name: Code Checkout
      uses: action/checkout@v3

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: True
        tags: ${{ secrets.DOCKER_USERNAME }}/IRIS_ML_APP:$(date +%s)

  